sudo: required

services:
- docker

before_install:
- docker pull centos:7.5.1804

script:
- >
  docker run -t --rm -v ${PWD}/rpms:/rpms centos:7.5.1804
  bash -c
  "yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm &&
   yum install -y https://download.ceph.com/rpm-hammer/el7/noarch/ceph-release-1-0.el7.noarch.rpm &&
   mkdir -p /rpms &&
   yum remove -y python-chardet &&
   yum -y install --downloadonly --downloaddir=/rpms ceph-deploy ceph ceph-radosgw rbd-nbd rbd-mirror open-vm-tools  nfs-utils && 
   yum install -y createrepo &&
   yum clean all &&
   createrepo /rpms"
- sudo chmod -R 755 ${PWD}/rpms
- docker build -t wise2c/yum-repo-ceph:$TRAVIS_BRANCH .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push wise2c/yum-repo-ceph:$TRAVIS_BRANCH
