sudo: required

services:
- docker

before_install:
#- docker pull centos:7.4.1708
#- docker pull centos:7.5.1804
- docker pull centos:7.6.1810

env:
 global:
   #- CEPH_VERSION=nautilus
   #- KUBE_VERSION=1.16.3
   - DOCKER_VERSION=18.09.9-3
 
script:
- >
  
 

- docker images 
- docker pull jumpserver/jms_koko:2.0.0
- docker tag jumpserver/jms_koko:2.0.0 37705109/jms_koko:2.0.0
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push 37705109/jms_koko:2.0.0
