sudo: required

services:
- docker

before_install:
#- docker pull centos:7.4.1708
#- docker pull centos:7.5.1804
- docker pull centos:7.6.1810

env:
 global:
   #- CEPH_VERSION=nautilus
   #- KUBE_VERSION=1.16.3
   - DOCKER_VERSION=18.09.9-3
 
script:
- >
  
 

- docker images 
- docker pull k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
- docker tag k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1 registry.cn-hangzhou.aliyuncs.com/37705109/pgadmin:v1
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-hangzhou.aliyuncs.com
- docker push registry.cn-hangzhou.aliyuncs.com/37705109/pgadmin:v1
